name: pack and publish nuget
description: action for pack and publish nuget to nuget repository

inputs:
  nuget_api_key:
    required: true
    description: "nuget.org api key for publishing the nuget package"
  package_version:
    required: true
    description: "the version that was calculated"

runs:
  using: 'composite'
  
  steps:
    - name: calculate version
      id: calculate-version
      uses: bitshifted/git-auto-semver@v1
      with: 
        main_branch: master
        create_tag: true
          
    - name: pack the nuget package
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ steps.calculate-version.outputs.version-string }}
      shell: bash

    - name: publish nuget package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ inputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json
      shell: bash