name: pack and publish nuget
description: action for pack and publish nuget to nuget repository

inputs:
  nuget_api_key:
    required: true
    description: "nuget.org api key for publishing the nuget package"

runs:
  using: 'composite'
  
  steps:
    - name: Install GitVersion
      uses: GitTools/actions/gitversion/setup@vv1.2.0
      with:
        versionSpec: '5.x'

    - name: Get Version
      id: gitversion
      run: echo "::set-output name=version::$(gitversion /output json /showvariable NuGetVersionV2)"
      shell: bash

    - name: pack the nuget package
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ steps.gitversion.outputs.version }}
      shell: bash

    - name: publish nuget package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ inputs.nuget_api_key }} --source https://api.nuget.org/v3/index.json
      shell: bash