name: build, test, pack and publish nuget package on nuget repository

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: show and log
        run: echo ${{ github.event_name }}
      
      - name: show and log1
        run: echo ${{ github.ref_name }} 
