name: pack and publish nuget

on: 
  push:
    

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: build and test
        uses: ./.github/workflows/BuildTestWorkflow.yml
        